name: Play with GH actions

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          # components: clippy

      - name: dump
        run: |
          echo ___________________________________________________________________________________________________________
          echo $HOME
          echo $GITHUB_WORKSPACE
          echo ${{ github.workspace }}
          echo $CARGO_HOME
          ls -la $HOME/.cargo/bin
          ls -la $GITHUB_WORKSPACE
          ls -la ${{ github.workspace }}
