name: Play with GH actions

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PKG_NAME: apekey
      PKGBUILD: ./.pkg/aur/PKGBUILD
      RELEASE_TAG: v0.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: WIP
        run: ls -la
      - name: WIP
        run: sha256sum --version
      - name: WIP
        run: sha256sum apekey-v0.1.2.tar.gz
      - name: Update PKGBUILD
        run: ./.pkg/aur/update_pkgbuild.sh
